#define MQTT_BROKER_HOST "YOUR_MQTT_BROKER_HOST"
#define MQTT_BROKER_PORT 8883
#define MQTT_USERNAME "YOUR_MQTT_USERNAME"
#define MQTT_PASSWORD "YOUR_MQTT_PASSWORD"
#define MQTT_DEVICE_ID "aquasolar-device01"
