const state={ph:7.1,temp:25.4,humidity:60,level:78,distance:null,tds:250,oxygen:7.2,battery:null,pump:false,auto:true,status:'NORMAL',connected:false,esp32Url:localStorage.getItem('ranomadioEsp32Url')||'http://192.168.4.1',phMin:6.5,phMax:8.5,history:[],alerts:[],events:[],demo:false,lastSeen:null};
const $=id=>document.getElementById(id);const now=()=>new Date().toLocaleTimeString('fr-FR');const apiUrl=path=>state.esp32Url.replace(/\/$/,'')+path;
function addEvent(icon,title,detail){state.events.unshift({icon,title,detail,time:now()});state.events=state.events.slice(0,8);renderEvents()}
function addAlert(icon,title,detail){state.alerts.unshift({icon,title,detail,time:now()});state.alerts=state.alerts.slice(0,50);renderAlerts()}
function classify(){if(state.status==='CRITIQUE')return'danger';return state.ph<state.phMin||state.ph>state.phMax?'danger':'normal'}
function levelFromDistance(distance){if(distance==null||distance<0)return null;return Math.max(0,Math.min(100,100-(distance/35)*100))}
function updateConnection(connected){const changed=state.connected!==connected;state.connected=connected;const dot=document.querySelector('.connection .dot');if(dot)dot.className='dot '+(connected?'online':'offline');if($('connectionText'))$('connectionText').textContent=connected?`Connecté · ${state.esp32Url}`:'ESP32 hors ligne';if($('connectionBadge')){$('connectionBadge').textContent=connected?'EN LIGNE':'HORS LIGNE';$('connectionBadge').className='badge '+(connected?'':'danger')}document.querySelectorAll('.equipment b').forEach(el=>{if(el.parentElement?.textContent.includes('ESP32')){el.textContent=connected?'EN LIGNE':'HORS LIGNE';el.className=connected?'ok':'bad'}});if(changed)addEvent(connected?'🟢':'🔴',connected?'ESP32 connecté':'Connexion ESP32 perdue',connected?state.esp32Url:'Aucune réponse de l’ESP32')}
function updateStatus(){const bad=classify()==='danger';const critical=state.status==='CRITIQUE'||(state.level!=null&&state.level<15);$('waterStatus').textContent=critical?'ÉTAT CRITIQUE':bad?'EAU À TRAITER':'EAU PROPRE';$('statusIcon').textContent=critical?'🔴':bad?(state.pump?'🟡':'🔴'):'🟢';$('statusMessage').textContent=critical?'Traitement bloqué ou niveau critique.':bad?(state.pump?'Traitement automatique en cours.':'Anomalie détectée : traitement requis.'):'Les paramètres sont dans la plage configurée.';$('statusCard').style.background=critical?'linear-gradient(135deg,#fff0f0,#fff)':bad?'linear-gradient(135deg,#fff5e7,#fff)':'linear-gradient(135deg,#e8fbf2,#fff)';$('phBadge').textContent=bad?'ANOMALIE':'NORMAL';$('phBadge').className='badge '+(bad?'danger':'');$('pumpState').textContent=state.pump?'EN FONCTIONNEMENT':'ARRÊTÉE';$('pumpEquipment').textContent=state.pump?'EN FONCTIONNEMENT':'ARRÊTÉE';$('processTreatment').className='process-step '+(state.pump?'active':'');$('processDone').className='process-step '+(!state.pump&&!bad?'done':'');if(state.level==null)$('levelMessage').textContent='Mesure indisponible';else $('levelMessage').textContent=state.level<15?'Niveau critique — pompe bloquée':state.level<30?'Niveau faible':'Niveau suffisant';if(state.level!=null)$('levelMeter').style.width=state.level+'%';$('phMeter').style.width=Math.max(0,Math.min(100,((state.ph-4)/7)*100))+'%';$('batteryMeter').style.width=state.battery==null?'0%':state.battery+'%';$('batteryValue').textContent=state.battery==null?'N/D':Math.round(state.battery);$('batteryBadge').textContent=state.battery==null?'NON DISPONIBLE':state.battery<20?'FAIBLE':'BONNE';$('batteryBadge').className='badge '+(state.battery==null?'neutral':state.battery<20?'warning':'');if($('tdsValue')){$('tdsValue').textContent=Number.isFinite(state.tds)?Math.round(state.tds):'N/D';$('tdsBadge').textContent=state.tds>500?'ÉLEVÉ':'NORMAL';$('tdsBadge').className='badge '+(state.tds>500?'danger':'')}if($('oxygenValue')){$('oxygenValue').textContent=Number.isFinite(state.oxygen)?state.oxygen.toFixed(1):'N/D';$('oxygenBadge').textContent=state.oxygen<4?'FAIBLE':'BON';$('oxygenBadge').className='badge '+(state.oxygen<4?'danger':'')}}
function renderMetrics(){$('phValue').textContent=Number.isFinite(state.ph)?state.ph.toFixed(2):'N/D';$('tempValue').textContent=Number.isFinite(state.temp)?state.temp.toFixed(1):'N/D';$('humidityValue').textContent=Number.isFinite(state.humidity)?Math.round(state.humidity):'N/D';$('levelValue').textContent=state.level==null?'N/D':Math.round(state.level);$('lastUpdate').textContent=state.lastSeen?new Date(state.lastSeen).toLocaleTimeString('fr-FR'):now();updateStatus();drawCharts()}
function renderEvents(){$('eventsList').innerHTML=state.events.map(e=>`<div class="event"><span class="eicon">${e.icon}</span><div><b>${e.title}</b><small>${e.detail} · ${e.time}</small></div></div>`).join('')||'<div class="event">Aucun événement</div>'}
function renderAlerts(){$('alertsList').innerHTML=state.alerts.map(a=>`<div class="alert-item"><div class="aicon">${a.icon}</div><div><b>${a.title}</b><small>${a.detail} · ${a.time}</small></div></div>`).join('')||'<div class="panel">Aucune alerte enregistrée.</div>'}
function renderHistory(){$('historyBody').innerHTML=state.history.slice().reverse().map(h=>`<tr><td>${h.time}</td><td>${h.ph.toFixed(2)}</td><td>${h.temp.toFixed(1)} °C</td><td>${h.humidity!=null?Math.round(h.humidity)+' %':'N/D'}</td><td>${h.level!=null?Math.round(h.level)+' %':'N/D'}</td><td>${Number.isFinite(h.tds)?Math.round(h.tds)+' ppm':'N/D'}</td><td>${Number.isFinite(h.oxygen)?h.oxygen.toFixed(1)+' mg/L':'N/D'}</td><td>${h.status}</td></tr>`).join('')}
function drawLineChart(id,values,opts={}){const c=$(id);if(!c)return;const ctx=c.getContext('2d'),w=c.clientWidth||700,h=c.clientHeight||240,dpr=window.devicePixelRatio||1;c.width=w*dpr;c.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const vals=values.filter(v=>Number.isFinite(v));if(vals.length<2){ctx.fillStyle='#8da099';ctx.font='13px system-ui';ctx.fillText('En attente de données…',24,h/2);return}let min=opts.min??Math.min(...vals),max=opts.max??Math.max(...vals);if(max===min){min-=1;max+=1}const pad={l:46,r:16,t:18,b:30},pw=w-pad.l-pad.r,ph=h-pad.t-pad.b;ctx.strokeStyle='#e5eeea';ctx.lineWidth=1;for(let i=0;i<5;i++){const y=pad.t+i*ph/4;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();const label=max-(max-min)*i/4;ctx.fillStyle='#8da099';ctx.font='10px system-ui';ctx.fillText(label.toFixed(opts.decimals??1),5,y+3)}const data=values.slice(-30);ctx.strokeStyle=opts.stroke||'#15a36a';ctx.lineWidth=2.5;ctx.beginPath();data.forEach((v,i)=>{const x=pad.l+(i/(data.length-1))*pw,y=pad.t+(max-v)/(max-min)*ph;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle=opts.stroke||'#15a36a';data.forEach((v,i)=>{const x=pad.l+(i/(data.length-1))*pw,y=pad.t+(max-v)/(max-min)*ph;ctx.beginPath();ctx.arc(x,y,2.5,0,Math.PI*2);ctx.fill()})}
function drawCharts(){drawLineChart('phChart',state.history.map(x=>x.ph),{min:6,max:9,decimals:1});drawLineChart('tdsChart',state.history.map(x=>x.tds),{min:0,decimals:0});drawLineChart('oxygenChart',state.history.map(x=>x.oxygen),{min:0,decimals:1});drawLineChart('tempChart',state.history.map(x=>x.temp),{min:15,decimals:1})}
function recordMeasurement(){const bad=classify()==='danger';state.history.push({time:now(),ph:state.ph,temp:state.temp,humidity:state.humidity,level:state.level,tds:state.tds,oxygen:state.oxygen,battery:state.battery,status:state.status||(bad?'À traiter':'Propre')});state.history=state.history.slice(-100);renderHistory()}
async function fetchEsp32(){try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),2500);const response=await fetch(apiUrl('/api/status'),{cache:'no-store',signal:controller.signal});clearTimeout(timer);if(!response.ok)throw new Error('HTTP '+response.status);const d=await response.json();const previousPump=state.pump,previousStatus=state.status;state.ph=Number(d.ph);state.temp=Number(d.temperature);state.humidity=Number(d.humidity);state.distance=d.distance==null?null:Number(d.distance);state.level=d.waterLevel!=null?Number(d.waterLevel):levelFromDistance(state.distance);state.tds=d.tds==null||Number(d.tds)<0?null:Number(d.tds);state.oxygen=d.oxygen==null||Number(d.oxygen)<0?null:Number(d.oxygen);state.pump=Boolean(d.pump);state.status=d.status||((state.ph<state.phMin||state.ph>state.phMax)?'ANORMAL':'NORMAL');state.lastSeen=d.timestamp?d.timestamp:Date.now();state.battery=d.battery==null?null:Number(d.battery);state.demo=false;updateConnection(true);renderMetrics();recordMeasurement();if(previousPump!==state.pump)addEvent(state.pump?'🟡':'🟢',state.pump?'Pompe activée':'Pompe arrêtée',state.pump?'Traitement en cours':'Traitement terminé');if(previousStatus!==state.status&&state.status!=='NORMAL')addAlert('🔴','Qualité de l’eau anormale',`État ESP32 : ${state.status}`);if(state.tds!=null&&state.tds>500)addAlert('🧪','TDS élevé',`Solides dissous : ${Math.round(state.tds)} ppm`);if(state.oxygen!=null&&state.oxygen<4)addAlert('🫧','Oxygène dissous faible',`Oxygène : ${state.oxygen.toFixed(1)} mg/L`);if(state.level!=null&&state.level<15)addAlert('⚠️','Niveau critique','La pompe doit rester arrêtée pour protéger le système.')}catch(e){updateConnection(false);if(!state.demo){state.demo=false;renderMetrics()}}}
function simulate(){if(state.connected)return;state.demo=true;state.ph=+(6.8+Math.random()*1).toFixed(2);state.temp=+(24.2+Math.random()*3.2).toFixed(1);state.humidity=Math.round(55+Math.random()*20);state.level=Math.max(8,state.level+(Math.random()-.46)*2);state.tds=Math.round(180+Math.random()*260);state.oxygen=+(5.2+Math.random()*3).toFixed(1);state.battery=null;state.pump=false;state.status=state.ph<state.phMin||state.ph>state.phMax?'ANORMAL':'NORMAL';renderMetrics();recordMeasurement()}
async function testConnection(){await fetchEsp32()}
function setView(view){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));$(view).classList.add('active-view');document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'});if(view==='history')drawCharts()}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll('[data-view-target]').forEach(b=>b.onclick=()=>setView(b.dataset.viewTarget));
$('notifyBtn').onclick=()=>alert(state.alerts.length?`${state.alerts.length} événement(s) dans l'historique.`:'Aucune nouvelle alerte.');
$('autoBtn').onclick=()=>{state.auto=!state.auto;$('autoBtn').classList.toggle('on',state.auto);$('autoBtn').firstChild.textContent=state.auto?'AUTO ':'MANUEL ';$('modeLabel').textContent=state.auto?'AUTOMATIQUE':'MANUEL'};
$('autoSetting').onclick=()=>{$('autoBtn').click();$('autoSetting').classList.toggle('on',state.auto);$('autoSetting').firstChild.textContent=state.auto?'AUTO ':'OFF '};$('notifSetting').onclick=()=>{$('notifSetting').classList.toggle('on');$('notifSetting').firstChild.textContent=$('notifSetting').classList.contains('on')?'ON ':'OFF '};
$('saveSettings').onclick=async()=>{state.phMin=parseFloat($('phMin').value);state.phMax=parseFloat($('phMax').value);localStorage.setItem('ranomadioPhMin',state.phMin);localStorage.setItem('ranomadioPhMax',state.phMax);addEvent('⚙️','Seuils mis à jour',`pH ${state.phMin} — ${state.phMax}`);updateStatus();if(state.connected){try{await fetch(apiUrl('/api/config'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phMin:state.phMin,phMax:state.phMax})})}catch(e){addAlert('⚠️','Configuration non envoyée','Vérifiez la connexion ESP32')}}alert('Configuration enregistrée.')};$('clearAlerts').onclick=()=>{state.alerts=[];renderAlerts()};
$('exportBtn').onclick=()=>{let csv='Date,pH,Temperature,Humidite,Niveau,TDS_ppm,Oxygene_mgL,Etat\n'+state.history.map(h=>`${h.time},${h.ph},${h.temp},${h.humidity??''},${h.level==null?'':Math.round(h.level)},${h.tds==null?'':Math.round(h.tds)},${h.oxygen==null?'':h.oxygen},${h.status}`).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='aquasolar-historique.csv';a.click()};
$('connectEsp32').onclick=async()=>{const value=$('esp32Url').value.trim().replace(/\/$/,'');if(!value)return alert('Indiquez l’adresse IP de l’ESP32.');state.esp32Url=value;localStorage.setItem('ranomadioEsp32Url',value);await testConnection()};$('year').textContent=new Date().getFullYear();state.phMin=parseFloat(localStorage.getItem('ranomadioPhMin')||'6.5');state.phMax=parseFloat(localStorage.getItem('ranomadioPhMax')||'8.5');$('phMin').value=state.phMin;$('phMax').value=state.phMax;$('esp32Url').value=state.esp32Url;
addEvent('🟢','Système initialisé','TDS et oxymètre intégrés · graphiques de qualité de l’eau activés');renderEvents();renderAlerts();renderHistory();renderMetrics();fetchEsp32();setInterval(fetchEsp32,4000);setInterval(simulate,4000);
const aquaEnhance=document.createElement('script');aquaEnhance.src='presentation-mode.js';document.body.appendChild(aquaEnhance);const aquaStyle=document.createElement('link');aquaStyle.rel='stylesheet';aquaStyle.href='presentation-mode.css';document.head.appendChild(aquaStyle);